version: "3"
services:
  server:
    image: wgandino/codenames
    ports:
      - 8810:8810
    environment:
      - NO_CONSOLE_COLORS=1
      - CODENAMES_HTTP_PORT=8810
    deploy:
      mode: replicated
      replicas: 2
#    volumes:
#      - ./dist/data:/svc/codenames/data:rw
