# fly.toml app configuration file generated for codenames-ucab-proyecto on 2023-07-19T03:37:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codenames-ucab-proyecto"
primary_region = "mia"

[http_service]
  internal_port = 8810
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
